### ISSUE TITLE
Q: This Example works only for System.Windows.Forms.Controls

### ISSUE THREAD

**Issue by mdawid-cpn** [DevExpress-Examples/show-super-tooltip-for-disabled-controls-e521#1]
The given example works only for Controls that have the Bounds.Contains method (namespace System.Windows.Forms). But what if i use DevExpress controls like controls that derive from DevExpress.XtraEditors.ButtonPanel.IBaseButton?

**Comment by LexEPoX** [comment]
Hello,
 
The required functionality can be achieved at the descendant level. To do so, create an inherited [WindowsUIButtonPanel](https://documentation.devexpress.com/WindowsForms/DevExpress.XtraBars.Docking2010.WindowsUIButtonPanel.class) and implement the **DevExpress.Utils.IToolTipControlClient** interface as shown below:
```
   public class CustomWindowsUIButtonPanel : WindowsUIButtonPanel, IToolTipControlClient {
        public CustomWindowsUIButtonPanel() { }
        public BaseButtonInfo CalcHitInfo(Point pt, bool findDisabledButtons = false) {
            foreach (BaseButtonInfo buttonInfo in ButtonsPanel.ViewInfo.Buttons) {
                if (buttonInfo.Bounds.Contains(pt) && (!buttonInfo.Disabled || findDisabledButtons))
                    return buttonInfo;
            }
            return null;
        }
        public new ToolTipControlInfo GetObjectInfo(Point point) {
            ToolTipControlInfo result = null;
            BaseButtonInfo buttoInfo = CalcHitInfo(point, true);
            if (buttoInfo != null && (!string.IsNullOrEmpty(buttoInfo.Button.Properties.ToolTip) || buttoInfo.Button.Properties.SuperTip != null)) {
                result = new ToolTipControlInfo(buttoInfo.Button.Properties, buttoInfo.Button.Properties.ToolTip);
                result.SuperTip = buttoInfo.Button.Properties.SuperTip != null ? buttoInfo.Button.Properties.SuperTip : null;
            }
            return result;
        }
    }
```
After that, tooltips will be automatically shown for disabled [WindowsUIButtons](https://documentation.devexpress.com/WindowsForms/DevExpress.XtraBars.Docking2010.WindowsUIButton.class) as well.

**Comment by mdawid-cpn** [comment]
Thanks, this solution worked for me!! 👍
